// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: "html",
      value: `<p class="menu-category" style="color: var(--ifm-color-secondary-darkest)">入门</p>`,
      defaultStyle: true, // Use the default menu item styling
    },
    "introduction",
    "api-overview",
    "choice-endpoints",
    {
      type: "html",
      value: `<p class="menu-category" style="color: var(--ifm-color-secondary-darkest)">指南</p>`,
      defaultStyle: true, // Use the default menu item styling
    },
    "guides/contexts",
    "guides/clone",
    "guides/best-practices",
    {
      type: "html",
      value: `<p class="menu-category" style="color: var(--ifm-color-secondary-darkest)">整合</p>`,
      defaultStyle: true, // Use the default menu item styling
    },
    "price",
    "voices",
    "faqs"
  ],
  api : [
    {
      type: "html",
      value: `<p class="menu-category" style="color: var(--ifm-color-secondary-darkest)">使用 API</p>`,
      defaultStyle: true, // Use the default menu item styling
    },
    "api/introduction",
    "api/websocket",
    "api/limits-and-timeouts",
    "api/errors",
    {
      type: "html",
      value: `<p class="menu-category" style="color: var(--ifm-color-secondary-darkest)">TTS</p>`,
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'autogenerated',
      dirName: 'api/speech',
    },
    {
      type: "html",
      value: `<p class="menu-category" style="color: var(--ifm-color-secondary-darkest)">Voices</p>`,
      defaultStyle: true, // Use the default menu item styling
    },
    {
      type: 'autogenerated',
      dirName: 'api/voices',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
